import numpy as np
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x)
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x / 2)

A = np.array([[1,2], [3,4]])
B = np.array([[3,0], [0,6]])
print(A)
print(A + B)
print(A - B)
print(A * B)
print(A / B)

C = np.array([10, 20])
print(A + C)
print(A - C)
print(A * C)
print(A / C)

A = np.array([[51, 55], [14, 19], [0, 4]])
print(A)
print(A[0])
print(A[0][1])
for row in A:
    print(row)
A = A.flatten()
print(A)
print(A[np.array([0, 2, 4])])
print(A > 15)
print(A[A > 15])